language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

install:
  - true

script:
  - ./gradlew clean build check

notifications:
  email:
    - thibault.le.mansec@gmail.com